from __future__ import annotations

import re

from core.protocols import WorkflowContext
from core.schemas import DiffResult, GeneratedFile, GenerationResult

SUPPORTED_MINIMAL_OPS = {"open", "read", "write", "lseek", "getdents64", "ioctl", "mmap", "poll"}
PROC_AUTO_CONST_TEXT = """# Code generated by hm-ai-fuzz syz-description-agent. DO NOT EDIT.
arches = 386, amd64, arm, arm64, mips64le, ppc64le, riscv64, s390x
AT_FDCWD = 18446744073709551516
__NR_getdents64 = 61, 386:s390x:220, amd64:arm:217, mips64le:5308, ppc64le:202
__NR_lseek = 19, amd64:8, arm64:riscv64:62, mips64le:5008
__NR_openat = 56, 386:295, amd64:257, arm:322, mips64le:5247, ppc64le:286, s390x:288
__NR_read = 3, amd64:0, arm64:riscv64:63, mips64le:5000
__NR_write = 4, amd64:1, arm64:riscv64:64, mips64le:5001
"""


class MinimalSyzkallerGeneratePlugin:
    name = "minimal-syzkaller"

    def generate(self, diff: DiffResult, ctx: WorkflowContext) -> GenerationResult:
        if ctx.syzkaller_dir is None:
            raise ValueError("syzkaller_dir is required for syzkaller generation")
        sys_linux_dir = ctx.syzkaller_dir / "sys" / "linux"
        sys_linux_dir.mkdir(parents=True, exist_ok=True)
        txt_name = str(ctx.config.get("txt_name", "proc_auto.txt"))
        txt_path = sys_linux_dir / txt_name
        const_path = txt_path.with_suffix(txt_path.suffix + ".const")

        entries = _collect_entries(diff.new_items)
        txt_path.write_text(render_proc_auto_txt(entries), encoding="utf-8")
        const_path.write_text(PROC_AUTO_CONST_TEXT, encoding="utf-8")

        metadata = {
            "generated_interface_count": len(entries),
            "skipped_interface_count": max(0, len(diff.new_items) - len(entries)),
            "txt_path": str(txt_path),
            "const_path": str(const_path),
        }
        return GenerationResult(
            generated_files=[
                GeneratedFile(path=str(txt_path), kind="txt", details={"entry_count": len(entries)}),
                GeneratedFile(path=str(const_path), kind="txt.const", details={"entry_count": 6}),
            ],
            units=[
                {
                    "target": entry["target"],
                    "supported_ops": entry["supported_ops"],
                    "resource_name": entry["resource_name"],
                    "open_alias": entry["open_alias"],
                    "kind": entry["kind"],
                }
                for entry in entries
            ],
            metadata=metadata,
        )

def _collect_entries(new_items: list[dict[str, object]]) -> list[dict[str, object]]:
    by_target: dict[str, dict[str, object]] = {}
    for item in new_items:
        target = item.get("target")
        op = item.get("op")
        if not isinstance(target, str) or not isinstance(op, str):
            continue
        if op not in SUPPORTED_MINIMAL_OPS:
            continue
        entry = by_target.setdefault(
            target,
            {
                "target": target,
                "supported_ops": [],
                "kind": item.get("node_type") if isinstance(item.get("node_type"), str) else "file",
            },
        )
        if op not in entry["supported_ops"]:
            entry["supported_ops"].append(op)
    entries: list[dict[str, object]] = []
    for target, entry in sorted(by_target.items()):
        safe = _safe_name(target)
        is_dir = entry["kind"] in {"dir", "virtual_dir"} or "getdents64" in entry["supported_ops"]
        entries.append(
            {
                "target": target,
                "supported_ops": sorted(entry["supported_ops"]),
                "kind": entry["kind"],
                "resource_name": "fd_dir" if is_dir else f"fd_proc_{safe}",
                "open_alias": f"openat$proc_{safe}",
            }
        )
    return entries


def render_proc_auto_txt(entries: list[dict[str, object]]) -> str:
    lines = [
        "# Auto-generated by hm-ai-fuzz syz-description-agent.",
        "# Minimal proc coverage: generate openat aliases and reuse generic read/write/lseek/getdents64/ioctl/mmap/poll.",
        "",
        "include <uapi/linux/fcntl.h>",
        "",
    ]
    resources = sorted({str(entry["resource_name"]) for entry in entries if entry["resource_name"] != "fd_dir"})
    for resource in resources:
        lines.append(f"resource {resource}[fd]")
    if resources:
        lines.append("")
    poll_entries = [entry for entry in entries if "poll" in entry["supported_ops"]]
    for entry in poll_entries:
        safe = _safe_name(str(entry["target"]))
        lines.append(f"pollfd$proc_{safe} {{")
        lines.append(f"\tfd\t{entry['resource_name']}")
        lines.append("\tevents\tint16")
        lines.append("\trevents\tint16")
        lines.append("}")
        lines.append("")
    for entry in entries:
        target = str(entry["target"])
        ops = ",".join(entry["supported_ops"])
        lines.append(f"# {target} [{ops}]")
        lines.append(
            f"{entry['open_alias']}(fd const[AT_FDCWD], file ptr[in, string[\"{target}\"]], "
            f"flags flags[open_flags], mode const[0]) {entry['resource_name']}"
        )
        safe = _safe_name(target)
        resource_name = str(entry["resource_name"])
        if "read" in entry["supported_ops"] and resource_name != "fd_dir":
            lines.append(f"read$proc_{safe}(fd {resource_name}, buf buffer[out], count len[buf])")
        if "write" in entry["supported_ops"] and resource_name != "fd_dir":
            lines.append(f"write$proc_{safe}(fd {resource_name}, buf buffer[in], count len[buf])")
        if "lseek" in entry["supported_ops"] and resource_name != "fd_dir":
            lines.append(
                f"lseek$proc_{safe}(fd {resource_name}, offset fileoff, "
                "whence flags[seek_whence]) (ignore_return)"
            )
        if "ioctl" in entry["supported_ops"] and resource_name != "fd_dir":
            lines.append(f"ioctl$proc_{safe}(fd {resource_name}, cmd int32, arg buffer[in])")
        if "mmap" in entry["supported_ops"] and resource_name != "fd_dir":
            lines.append(
                f"mmap$proc_{safe}(addr vma, len len[addr], prot flags[mmap_prot], "
                f"flags flags[mmap_flags], fd {resource_name}, offset intptr[0:0xffffffff, 0x1000])"
            )
        if "poll" in entry["supported_ops"]:
            lines.append(f"poll$proc_{safe}(ufds ptr[inout, pollfd$proc_{safe}], nfds len[ufds], timeout_msecs int32)")
        lines.append("")
    if not entries:
        lines.append("# no supported proc interfaces were available for minimal generation")
        lines.append("")
    return "\n".join(lines)


def _safe_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]+", "_", value.strip("/")) or "proc"
